# Generated by Django 4.1.4 on 2023-03-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='aa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='ammo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='armor',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='asw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='avi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='eva',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='faction',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='fp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='lck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='oil',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='oxy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='rarity',
            field=models.CharField(default='N/A', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='rld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='sid',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='spd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='trp',
            field=models.IntegerField(default=0),
        ),
    ]
